name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      DOCKER_USERNAME: thatchayaini123
      IMAGE_NAME: jun20old
      TAG: latest
      CONTAINER_NAME: mycontainer
      PORT: 3000

    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v4

      - name: ⚙️ Build Docker Image
        run: |
          docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$TAG -f Dockerfile .

      - name: 🧹 Remove Old Container If Exists
        run: |
          if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]_]()






