name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      DOCKER_USERNAME: thatchayaini123
      IMAGE_NAME: jun20
      TAG: latest
      CONTAINER_NAME: mycontainer
      PORT: 3000

    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v4

      - name: ⚙️ Build Docker Image
        run: |
          docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$TAG -f jun21/jun21demo/Dockerfile jun21/jun21demo

      - name: 🧹 Remove Old Container If Exists
        run: |
          if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
          fi

      - name: 🚀 Run Docker Container
        run: |
          docker run -d --name $CONTAINER_NAME -p $PORT:$PORT $DOCKER_USERNAME/$IMAGE_NAME:$TAG

      - name: 📤 Push to Docker Hub
        run: |
          docker push $DOCKER_USERNAME/$IMAGE_NAME:$TAG


